<? $page="Credit Tips"; ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Qwest Credit Enhancement | <?php echo $page; ?></title>
<? include("inc/global-header-data.php"); ?>
</head>
<body>
	<div id="container">
		<div id="hdr">
<? include("inc/content-header.php"); ?>
		</div>
		<div id="content">
		<div id="main-content">
		<!-- content begins here -->
		<h1><em>Credit Tips</em></h1>
		<h2>What is a Credit Score?</h2>
		<p>A credit score is a number generated by a mathematical formula that is meant to predict credit worthiness. The most common of the credit score standards is the FICO score by Fair Isaac. The FICO score ranges from 350-850 and is intended as a predictor of whether or not you will be 90 days late on a loan obligation. Fair Isaac uses thousands of credit reports to calibrate the FICO scoring model and is very secretive of the exact formula.</p>
		<p>Here is a percentage breakdown of a FICO score:</p>
		<ul>
			<li>35% - Payment History</li>
			<li>30% - Debt Ratio</li>
			<li>15% - Length of Credit History</li>
			<li>10% - Types of Credit</li>
			<li>10% - Number of Credit Inquiries</li>
		</ul>
		<p>Most people are aware of the three credit reporting agencies TransUnion, Equifax and Experian. The average difference in score between the highest and lowest of your three FICO scores is 60 points. This is the result of each of the credit bureaus having different items on their report. some correct, some incorrect and some that are not being reported in full compliance with credit law.</p>
		<p>According to the Government Accountability Office, 80-90% of credit reports have serious errors on them, be sure to check your report frequently.  How can I find out my credit score?  Visit <a href="http://www.myfico.com">www.myfico.com</a> and order the same credit score a mortgage company uses for approvals. Requests for one&#39;s own FICO score at <a href="http://www.myfico.com">www.myfico.com</a> is considered a personal inquiry and will not hurt the credit score. How can I get a free copy of my credit report? By law, all consumers are entitled to a free copy of their credit report from each of the three credit bureaus once a year. Visit www.annualcreditreport.com to get yours for <em>FREE</em>. (We encourage you not to use this site to obtain your report. if you do, the bureaus will have 45 days, instead of 30,  to verify any disputes).</p>
		<h2>How long will the items get reported on my file?</h2>
		<ul>
			<li><strong>Delinquencies (30–180 days):</strong> Can remain seven years from the date of the initial missed payment.</li><br />
			<li><strong>Collection accounts:</strong> Remain seven years from the date of the initial missed payment that led to the collection (the original delinquency date). When a collection account is paid in full, it will be marked "paid collection" on the credit report.</li> <br />
			<li><strong>Charged-off accounts:</strong> Remain seven years from the date of the initial missed payment that led to the charge-off (the original delinquency date), even if payments are later made on the charged-off account.</li><br />
			<li><strong>Closed accounts:</strong> Closed accounts are accounts that are no longer available for further use. Closed accounts may or may not have a zero balance. Closed accounts with delinquencies remain seven years from the date they are reported closed, whether closed by the creditor or by the consumer, but the delinquency notation will be removed seven years after the delinquency occurred when pertaining to late payments. Positive closed accounts remain ten years from the closing date.</li><br />
			<li><strong>Lost credit card:</strong> If there are no delinquencies, credit cards that are reported lost will continue to be listed for two years from the date the card is reported lost. Delinquent payments that occurred before the card was lost are reported for seven years.</li><br />
			<li><strong>Bankruptcy:</strong> Chapters 7, 11, and 12 remain for ten years from the filing date. Chapter 13 remains seven years from the filing date. Accounts included in bankruptcy will remain seven years from the date they were reported as included in the bankruptcy.</li><br />
			<li><strong>Judgments:</strong> Remain seven years from the date the judgment is filed.</li><br />
			<li><strong>City, county, state, and federal tax liens:</strong> Unpaid tax liens remain fifteen years from the filing date. Paid tax liens remain seven years from the paid date of the lien.</li><br />
			<li><strong>Inquiries:</strong> Most inquiries listed on your credit report will remain for two years. Some inquiries, such as employment or pre-approved offers of credit, will show only on a personal credit report pulled by you.</li><br />
		</ul>
		  <h2>Is there anything that cannot be in my credit report?</h2><br />
			<p>Certain information cannot be in a credit report, including:</p>
			<ul>
				<li>Medical information (unless you give your consent)</li>
				<li>Notice of bankruptcy (Chapter 11) that is more than ten years old</li>
				<li>Debts (including delinquent child support payments) that are more than seven years old</li>
				<li>For California residents: records of arrest, information, or misdemeanor complaints must be removed after seven years. But under federal law, records of criminal convictions may remain on a credit report indefinitely.</li>
				<li>Age, marital status, or race (if the request is from a current or prospective employer</li>
			</ul>
		</div>
		<!-- end content -->
		</div>
		<div id="ftr">
<? include("inc/content-footer.php"); ?>
		</div>
	</div>
<? include("inc/global-ga.php"); ?>
</body>
</html>